GET http://localhost:3001/api/notes/3

###
POST http://localhost:3002/api/notes
Content-Type: application/json

{
    "content": "React is the best library for building UIs",
    "important": true
}

###
DELETE http://localhost:3002/api/notes/4


###
POST http://localhost:3002/api/login
Content-Type: application/application/json

{
    "username": "robert",
    "password": "gigel"
}


###
POST http://localhost:3002/api/notes
Content-Type: application/application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvYmVydCIsImlkIjoiNjFiOWZhMDRhZjVhYmQxY2ZjNmFiYWNmIiwiaWF0IjoxNjM5NjczMzUyfQ.ZR3YAWYmEzB0kgYbZBwQuUj6j3fdojNyVjzYIKfC6Wc

{
    "content": "Single page apps use token auth",
    "important": true
}